### ISSUE TITLE
Write counting software using YOLOv8 tracking and LoI

### ISSUE THREAD

**Issue by KamiCreed** [Salmon-Computer-Vision/salmon-computer-vision#58]
- [x] Look into how LOI is implemented
- [x] Implement Caltech's start/end trajectory based algorithm
- [x] Test software on a few test videos
- [x] Implement dataloader for image frames
- [x] Implement dataloader for Datumaro
- [x] Implement nMAE metric to evaluate model

**Comment by KamiCreed** [comment]
I discovered that there are some annotations in the Bear Creek data that had very thin boxes at the edge when the fish is already gone. An annotator must have forgotten to remove the annotation when the fish went away. This type annotation is prime to be removed through the thin boxes preprocessing step.

**Comment by KamiCreed** [comment]
Completed counting alg and nMAE metric. However, we found that the test set is sorely lacking in samples for proper evaluation, and the detection performs poorly in head/tail only detections. To fix these, we should add more samples and place a count threshold for the test set, and for the poor detections, we can ignore head/tail only detections when voting the species associated with the track ID.
